# Site settings
title: Shawn Duan
header-img: img/home-bg.jpg
copyright_name: Shawn(Wenxiao) Duan
description: "Welcome to my tech blog."
baseurl: ""
url: "http://shawn-duan.com/"
twitter_username: Shawn_Duan
weibo_username: duanwx
github_username:  ShawnDuan
linkedin_username: shawnwduan
facebook_username:  
email_username:  duan1216@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
